build-template: &build-template
    steps:
      - checkout

      - run:
          name: Validate composer file
          command: composer validate

      - run:
          name: Install dependencies
          command: make vendor

      - run:
          name: Run Tests
          command: |
            make coverage-test \
              mutation-test

      - run:
          name: Enforce Code Standards
          command: make code-standards

      - store_test_results:
          path: output

      - store_artifacts:
          path: output

version: 2
jobs:
  "php 7.1":
    <<: *build-template
    docker:
      - image: circleci/php:7.1-fpm-stretch
  "php 7.2":
    <<: *build-template
    docker:
      - image: circleci/php:7.2-fpm-stretch
  "php 7.3":
    <<: *build-template
    docker:
      - image: circleci/php:7.3-fpm-stretch

workflows:
  version: 2
  build:
    jobs:
      - "php 7.1"
      - "php 7.2"
      - "php 7.3"
